"""Deterministic citation attachment.

Citations are NEVER generated by the LLM.
They are built programmatically from selected chunk metadata only.
"""
from typing import List, Tuple


def attach_citations(selected_chunks: List[Tuple[float, dict]]) -> str:
    """Build citation string from selected chunk metadata.

    Args:
        selected_chunks: list of (score, metadata_dict) tuples

    Returns:
        Comma-separated citation string, or empty string if no chunks.
    """
    if not selected_chunks:
        return ""

    seen: List[str] = []
    for _, meta in selected_chunks:
        citation = f"[{meta['doc_name']} - Chunk {meta['chunk_id']}]"
        if citation not in seen:
            seen.append(citation)
    return ", ".join(seen)
